#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Append a generated LINEAGE block to every hand-written prose doc.

THE PROBLEM (Jake, 2026-08-25): a results document records a conclusion but not its
consequences. Reviewing e.g. PHASE_C_OPTION_B_N96_STAGE1_RESULTS months later, you cannot
tell which version of the simulation it ran against, what changed because of it, whether an
issue it raised was ever fixed, or whether a later document superseded it. The reader has to
reconstruct the aftermath by hand, which is exactly the work the document should have saved.

WHAT THIS DERIVES. Four independent signals, each with different coverage:

  1. Citation graph  - which LATER documents mention this one, and which earlier ones it cites.
                       Works for every doc regardless of git history. This is the strongest signal.
  2. Succession      - documents whose names indicate they follow this one (PLAN -> RESULTS,
                       STAGE1 -> STAGE2, V1 -> V2, _PILOT -> _VALIDATION, and so on).
  3. Catalog status  - what IRER_MASTER_HYPOTHESIS_CATALOG says about this doc, which is the
                       authority on whether its verdict is still live.
  4. Git             - introducing commit, revisions, and how much harness code has changed since.

> IMPORTANT COVERAGE LIMIT. The repository was clean-slated in commit 909e6e2 (2026-07-01).
> Every document written before that date shows only that commit, so git can say nothing about
> what changed for the whole June-era stability sector. The block states this explicitly rather
> than implying a lineage it cannot support.

WHAT IT DOES NOT DO. It cannot tell you WHY something changed, or whether an issue was actually
resolved - only that later documents exist and what they say. The semantic half belongs in the
"What changed as a result" and "Issues raised" sections of the doc itself (see
docs/DOCUMENTATION_METHODOLOGY.md and the templates).

SAFETY. Content is written between markers and regenerated in place. Everything outside the
markers is untouched. Run --strip to remove all blocks cleanly.

Usage:
    .venv/Scripts/python.exe tools/build_doc_lineage.py [--strip] [--dry-run]
"""
from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
from collections import defaultdict

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
VAULT = os.path.join(REPO, "docs")
BEGIN = "<!-- LINEAGE:BEGIN (generated by tools/build_doc_lineage.py - do not edit inside) -->"
END = "<!-- LINEAGE:END -->"

# Scope: the LIVE working documents. Deliberately excluded --
#   theory_synthesis/            archival transcript dossiers; "what changed after" is meaningless
#                                for a May-2025 conversation record
#   codex_conservative_c2_campaign_archive/  frozen archive, kept as-is by design
#   external research/           THIRD-PARTY documentation (ROCm/HIP) - never modify
#   runs/                        generated by build_run_catalogue.py, has its own lineage sections
INCLUDE_DIRS = ("", "gravity_maturity", "evidence_package", "external_validation")
SKIP_DIRS = {"runs", "_templates", ".obsidian", ".trash", "transcripts",
             "claud_memory_files", "past_variants", "theory_synthesis",
             "codex_conservative_c2_campaign_archive", "external research",
             "superpowers", "generated_reports", "legacy_colab_variants_pre-deployment_ R&d"}
CLEAN_SLATE = "2026-07-01"
CLEAN_SLATE_SHA = "909e6e2"

# name-succession patterns: (earlier marker, later marker, human label)
SUCCESSION = [
    ("_PLAN", "_RESULTS", "plan → results"),
    ("_DESIGN", "_RESULTS", "design → results"),
    ("_RFC", "_RESULTS", "RFC → results"),
    ("_PILOT", "_VALIDATION", "pilot → validation"),
    ("_PILOT", "_RESULTS", "pilot → results"),
    ("STAGE1", "STAGE2", "stage 1 → stage 2"),
    ("_V1", "_V2", "v1 → v2"),
    ("_FIRST", "_SECOND", "first → second"),
    ("_DOSSIER", "_FINAL_DOSSIER", "dossier → final dossier"),
]


def sh(*args):
    try:
        return subprocess.run(["git"] + list(args), cwd=REPO, capture_output=True,
                              text=True, encoding="utf-8", errors="replace").stdout
    except Exception:
        return ""


def prose_docs():
    out = []
    for root, dirs, files in os.walk(VAULT):
        dirs[:] = [d for d in dirs if d not in SKIP_DIRS and not d.startswith(".")]
        for f in files:
            if not f.endswith(".md"):
                continue
            rel = os.path.relpath(os.path.join(root, f), VAULT).replace(os.sep, "/")
            if os.path.basename(rel).startswith("_"):
                continue
            top = rel.rsplit("/", 1)[0] if "/" in rel else ""
            if top not in INCLUDE_DIRS:
                continue
            out.append(rel)
    return sorted(out)


def git_history(paths):
    """One pass over history: {relpath: [(sha, iso-date, subject)]} newest first."""
    hist = defaultdict(list)
    raw = sh("log", "--format=@@@%h|%ad|%s", "--date=short", "--name-only", "--", "docs/")
    sha = date = subj = None
    for line in raw.splitlines():
        if line.startswith("@@@"):
            parts = line[3:].split("|", 2)
            if len(parts) == 3:
                sha, date, subj = parts
        elif line.strip().startswith("docs/") and sha:
            rel = line.strip()[len("docs/"):]
            hist[rel].append((sha, date, subj))
    return hist


def code_commits_since(date):
    raw = sh("log", "--format=%h|%ad|%s", "--date=short", f"--since={date}", "--", "jax_scout/")
    rows = [l.split("|", 2) for l in raw.splitlines() if l.count("|") >= 2]
    return rows


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--strip", action="store_true", help="remove all lineage blocks and exit")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    docs = prose_docs()
    print("prose docs: %d" % len(docs))

    if args.strip:
        n = 0
        for rel in docs:
            p = os.path.join(VAULT, rel)
            t = open(p, encoding="utf-8").read()
            if BEGIN in t:
                t2 = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), "", t, flags=re.S).rstrip() + "\n"
                if not args.dry_run:
                    open(p, "w", encoding="utf-8").write(t2)
                n += 1
        print("stripped %d blocks" % n)
        return

    # ---- read all docs once -------------------------------------------------
    text, dates, stems = {}, {}, {}
    for rel in docs:
        p = os.path.join(VAULT, rel)
        try:
            t = open(p, encoding="utf-8", errors="replace").read()
        except OSError:
            continue
        body = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), "", t, flags=re.S)
        text[rel] = body
        stems[rel] = os.path.basename(rel)[:-3]
        m = re.search(r"^date:\s*(\d{4}-\d{2}-\d{2})", body, re.M)
        dates[rel] = m.group(1) if m else None

    hist = git_history(docs)
    for rel in docs:
        if dates.get(rel) is None:
            h = hist.get(rel)
            dates[rel] = h[-1][1] if h else "unknown"

    # ---- citation graph -----------------------------------------------------
    cited_by = defaultdict(list)
    cites = defaultdict(list)
    stem_to_rel = {}
    for rel in docs:
        stem_to_rel.setdefault(stems[rel], rel)
    # Generated index notes link to everything by construction; a link from an index is not a
    # downstream consequence, so they must not count as citation sources.
    GENERATED_INDEXES = {"DOC_LINEAGE", "EXPERIMENT_TRACKER", "HOME", "DOCUMENTATION_METHODOLOGY",
                         "META_ANALYSIS_BRANCH_PROGRESS"}
    for rel in docs:
        if stems[rel] in GENERATED_INDEXES or stems[rel].startswith("Branch - "):
            continue
        body = text[rel]
        for stem, target in stem_to_rel.items():
            if target == rel or len(stem) < 8:
                continue
            if stem in body:
                cites[rel].append(target)
                cited_by[target].append(rel)

    # ---- succession by name -------------------------------------------------
    succ = defaultdict(list)
    for rel in docs:
        s = stems[rel]
        for early, late, label in SUCCESSION:
            if early in s:
                cand = s.replace(early, late)
                if cand in stem_to_rel:
                    succ[rel].append((stem_to_rel[cand], label))

    catalog = text.get("IRER_MASTER_HYPOTHESIS_CATALOG.md", "")

    # The catalog refers to results by VERDICT STRING and prose, not by document name -- it names
    # only a handful of docs explicitly. So "is this doc tracked?" must also ask whether any verdict
    # it reports appears in the catalog. Verdicts are ALL_CAPS_WITH_UNDERSCORES tokens.
    VERD = re.compile(r"([A-Z][A-Z0-9]*(?:_[A-Z0-9]+){2,})")
    doc_verdicts = {}
    for rel in docs:
        body = text[rel]
        fm = re.search(r"^verdict:\s*(.+)$", body, re.M)
        vs = set()
        if fm:
            vs.add(fm.group(1).strip().strip('"'))
        for blk in re.findall("```text" + chr(10) + "(.*?)```", body, re.S):
            vs.update(VERD.findall(blk))
        vs.update(VERD.findall(body[:1500]))
        doc_verdicts[rel] = {v for v in vs if len(v) > 12}

    def catalog_status(rel):
        """(tracked_how, evidence) -- by name, by verdict, or not at all."""
        if stems[rel] in catalog:
            return "name", stems[rel]
        for v in sorted(doc_verdicts.get(rel, ()), key=len, reverse=True):
            if v in catalog:
                return "verdict", v
        return None, None

    written = 0
    for rel in docs:
        if stems[rel] in ("IRER_MASTER_HYPOTHESIS_CATALOG",):
            continue
        p = os.path.join(VAULT, rel)
        d = dates[rel] or "unknown"
        L = [BEGIN, "", "## Lineage — what changed after this", "",
             "> [!info] Generated by `tools/build_doc_lineage.py` — regenerated on each build.",
             "> It reports *that* later work exists, not *why* it happened. The reasoning belongs in",
             "> the **What changed as a result** and **Issues raised** sections above, written by hand.",
             ""]

        # --- version anchor
        h = hist.get(rel, [])
        if not h or (len(h) == 1 and h[0][1] <= CLEAN_SLATE):
            L += ["**Version written against:** unknown — this document predates the clean-slate "
                  "commit `%s` (%s), so git carries no history for it. Use the citation and "
                  "succession signals below instead." % (CLEAN_SLATE_SHA, CLEAN_SLATE), ""]
        else:
            first = h[-1]
            L += ["**Version written against:** `%s` (%s) — *%s*" % (first[0], first[1], first[2][:80])]
            if len(h) > 1:
                L += ["**Revised since:** %d commit(s), most recently `%s` (%s)"
                      % (len(h) - 1, h[0][0], h[0][1])]
            L += [""]
            cc = code_commits_since(first[1])
            if cc:
                L += ["**Harness code changed since it was written:** %d commit(s) to `jax_scout/`."
                      % len(cc)]
                L += ["  - `%s` %s — %s" % (c[0], c[1], c[2][:70]) for c in cc[:5]]
                if len(cc) > 5:
                    L += ["  - *…and %d more.*" % (len(cc) - 5)]
                L += [""]

        # --- consequences
        later = sorted({r for r in cited_by.get(rel, []) if (dates.get(r) or "") > d})
        earlier = sorted({r for r in cited_by.get(rel, []) if (dates.get(r) or "") <= d})
        if later:
            L += ["**Later documents that cite this one** — the downstream consequences:", ""]
            L += ["- [[%s]] &middot; `%s`" % (r[:-3], dates.get(r) or "?") for r in later[:12]]
            if len(later) > 12:
                L += ["- *…and %d more.*" % (len(later) - 12)]
            L += [""]
        else:
            L += ["**Later documents that cite this one:** none. "
                  "*Either this line of work stopped here, or the consequence was never written "
                  "down — both are worth knowing when reviewing it.*", ""]
        if earlier:
            L += ["**Also referenced by (same date or earlier):** "
                  + ", ".join("[[%s]]" % r[:-3] for r in earlier[:8]), ""]

        sc = succ.get(rel, [])
        if sc:
            L += ["**Named successors:** " + ", ".join("[[%s]] (*%s*)" % (t[:-3], lbl)
                                                       for t, lbl in sc), ""]

        # --- what the catalog says
        stem = stems[rel]
        how, ev = catalog_status(rel)
        if how == "verdict":
            hits = [re.sub(r"\s+", " ", ln).strip()[:300] for ln in catalog.splitlines() if ev in ln]
            L += ["**The master catalog tracks this by verdict** `%s` (not by document name — the "
                  "catalog refers to results by verdict string):" % ev, ""]
            L += ["> %s…" % x for x in hits[:1]]
            L += [""]
        elif how == "name":
            hits = []
            for line in catalog.splitlines():
                if stem in line:
                    txt = re.sub(r"\s+", " ", line).strip()
                    hits.append(txt[:300] + ("…" if len(txt) > 300 else ""))
            L += ["**The master catalog references this document** — the catalog is the authority "
                  "on whether its verdict is still live:", ""]
            L += ["> %s" % x for x in hits[:2]]
            L += [""]
        else:
            L += ["**Master catalog:** neither this document nor any verdict it reports appears in "
                  "the catalog. Its status is **not tracked centrally** — treat anything inside as "
                  "historical until confirmed.", ""]

        L += [END, ""]
        block = "\n".join(L)

        old = open(p, encoding="utf-8", errors="replace").read()
        if BEGIN in old:
            new = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n?", block, old, flags=re.S)
        else:
            new = old.rstrip() + "\n\n---\n\n" + block
        if new != old and not args.dry_run:
            open(p, "w", encoding="utf-8").write(new)
        written += 1

    # ---- overview note: turn the derived signals into a review worklist ------------------
    rows = []
    for rel in docs:
        stem = stems[rel]
        if stem == "IRER_MASTER_HYPOTHESIS_CATALOG":
            continue
        h = hist.get(rel, [])
        pre_cs = (not h) or (len(h) == 1 and h[0][1] <= CLEAN_SLATE)
        later = [r for r in cited_by.get(rel, []) if (dates.get(r) or "") > (dates.get(rel) or "")]
        in_cat = catalog_status(rel)[0] is not None
        has_wc = "## What changed as a result" in text[rel]
        rows.append((rel, dates.get(rel) or "?", pre_cs, len(later), in_cat, has_wc))

    dead = [r for r in rows if r[3] == 0]
    untracked = [r for r in rows if not r[4]]
    both = [r for r in rows if r[3] == 0 and not r[4]]
    L = ["---", "tags: [index, lineage]", "---", "", "# Document Lineage", "",
         "Generated by `tools/build_doc_lineage.py`. Every live working document carries a",
         "**Lineage** block reporting what came after it. This note aggregates those signals into a",
         "review worklist.", "",
         "> [!warning] What this can and cannot tell you",
         "> It reports *that* later work exists — citations, named successors, catalog references,",
         "> git history. It cannot tell you **why** something changed or whether an issue was",
         "> resolved. That belongs in each document's hand-written **What changed as a result** and",
         "> **Issues raised** sections. See [[DOCUMENTATION_METHODOLOGY]] §11.", "",
         "> [!danger] Coverage limit — the June-era docs have no git history",
         "> The repository was clean-slated in `%s` (%s). **%d of %d** documents predate it, so git"
         % (CLEAN_SLATE_SHA, CLEAN_SLATE, sum(1 for r in rows if r[2]), len(rows)),
         "> can say nothing about what changed for them. That includes the whole stability sector",
         "> currently under review ([[Branch - Stability - Review Checklist]]). For those, the",
         "> citation graph and the catalog are the only signals.", "",
         "## Summary", "", "| | count |", "|---|---:|",
         "| live working documents | %d |" % len(rows),
         "| **dead ends** — nothing later cites them | **%d** |" % len(dead),
         "| **untracked** — neither the doc nor its verdict appears in the catalog | **%d** |" % len(untracked),
         "| **both dead-end and untracked** | **%d** |" % len(both),
         "| no usable git history (pre clean-slate) | %d |" % sum(1 for r in rows if r[2]),
         "| carry a hand-written *What changed as a result* | %d |" % sum(1 for r in rows if r[5]),
         "", "> [!warning] 'Dead end' is a flag, not a verdict",
         "> Cross-referencing is sparse: 56% of documents name another document, at a mean of 1.6",
         "> references each. A document with no later citation may simply never have been named,",
         "> rather than never followed up. Treat the list below as a REVIEW QUEUE, resolved by",
         "> writing each entry's *What changed as a result* section — which is the actual fix.", "",
         "> [!danger] The catalog does not reference documents",
         "> `IRER_MASTER_HYPOTHESIS_CATALOG` names only a handful of documents explicitly; it refers",
         "> to results by **verdict string** and prose instead. This tool therefore also matches on",
         "> verdicts — and even so, **%d of %d** documents have neither their name nor any verdict" % (len(untracked), len(rows)),
         "> they report appearing in the catalog. **That is the structural reason a document cannot",
         "> tell you its own current status: the link from evidence to status was never made.**", "",
         "", "## Both a dead end and untracked", "",
         "*Nothing cites these and the catalog does not name them. Either the work stopped here and",
         "that was never recorded, or the consequence was never written down. Highest-value targets",
         "for a `What changed as a result` section.*", "",
         "| document | date | git history? |", "|---|---|---|"]
    for rel, d, pre, nl, cat, wc in sorted(both, key=lambda r: r[1], reverse=True)[:60]:
        L.append("| [[%s]] | %s | %s |" % (rel[:-3], d, "none (pre clean-slate)" if pre else "yes"))
    if len(both) > 60:
        L += ["", "*…and %d more.*" % (len(both) - 60)]
    L += ["", "## Dead ends that the catalog does track", "",
          "*The catalog knows about these, so their status is at least centrally recorded.*", "",
          "| document | date |", "|---|---|"]
    for rel, d, pre, nl, cat, wc in sorted([r for r in dead if r[4]],
                                           key=lambda r: r[1], reverse=True)[:40]:
        L.append("| [[%s]] | %s |" % (rel[:-3], d))
    L += ["", "---", "", "*Rebuild:* `.venv/Scripts/python.exe tools/build_doc_lineage.py`", ""]
    if not args.dry_run:
        open(os.path.join(VAULT, "DOC_LINEAGE.md"), "w", encoding="utf-8").write(chr(10).join(L) + chr(10))

    print("lineage blocks written: %d" % written)
    print("  dead-end AND untracked: %d" % len(both))
    orphans = [r for r in docs if not cited_by.get(r) and stems[r] != "IRER_MASTER_HYPOTHESIS_CATALOG"]
    print("docs nothing cites (dead ends): %d" % len(orphans))
    pre = [r for r in docs if not hist.get(r) or (len(hist[r]) == 1 and hist[r][0][1] <= CLEAN_SLATE)]
    print("docs with no usable git history (pre clean-slate): %d" % len(pre))


if __name__ == "__main__":
    sys.exit(main())
